version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: farm_products_db
      POSTGRES_USER: farm_seller
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - farmnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      RUNNING_IN_DOCKER: "True"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    networks:
      - farmnet

volumes:
  pgdata:
  staticfiles:
  media:

networks:
  farmnet:
