# Generated by Django 3.2.4 on 2021-07-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210726_1109'),
        ('products', '0003_auto_20210727_0940'),
    ]

    operations = [
    ]
