# Generated by Django 3.2.18 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251103_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kilos',
        ),
        migrations.AddField(
            model_name='product',
            name='available_kilos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How many kilograms are left in stock', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='kilos_ordered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How many kilograms were ordered', max_digits=8),
        ),
    ]
